# Generated by Django 5.1.3 on 2024-12-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateField()),
                ('FechaFinal', models.DateField()),
                ('EstadoReserva', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField()),
                ('Tier', models.IntegerField(choices=[(0, 'Básico'), (1, 'Intermedio'), (2, 'Avanzado')])),
                ('Nombres', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=20, unique=True)),
                ('Modelo', models.CharField(max_length=255)),
                ('Marca', models.CharField(max_length=255)),
                ('Año', models.IntegerField()),
                ('CantidadAsientos', models.IntegerField()),
                ('Tipo', models.CharField(max_length=255)),
                ('EstadoReserva', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('en_demora', 'En Demora'), ('falta', 'Falta')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Monto', models.FloatField()),
                ('MetodoDePago', models.CharField(max_length=255)),
                ('Banco', models.CharField(blank=True, max_length=255, null=True)),
                ('IdReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGo.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGo.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='IdVehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGo.vehiculo'),
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioDia', models.FloatField()),
                ('PrecioSemana', models.FloatField()),
                ('PrecioMes', models.FloatField()),
                ('IdVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGo.vehiculo')),
            ],
        ),
    ]
